-- Scope the forward-progress ledger's accrual to a reading *sitting*.
--
-- Migration `0083` differenced every position write against the last percent
-- observed, clamping a backward move to zero but still letting the mark follow
-- the reader back. Re-covering that ground then accrued a second time: at 40%,
-- flipping back to 30% to find a quote and returning to 45% charged 15 where
-- only 5 was new. It measured the *path* the reader walked, not the ground they
-- covered, so any backtracking inflated the Pages read tile and everything
-- derived from it.
--
-- The mark now holds the furthest point reached in the current sitting and
-- accrues only above it, so a there-and-back move inside one sitting is free.
--
-- A sitting ends after `stats::sessionize::IDLE_GAP_SECS` of no observation,
-- and that boundary governs the **mark**, never the gain. It is the only thing
-- that lets the mark fall back, which is what keeps a deliberate re-read
-- counting in full: restarting a finished book re-baselines at 5%, not a doomed
-- climb back to a lifetime high-water of 100. Ground beyond the mark is earned
-- on either side of it — an offline stretch coalesces into one write stamped
-- with the last page turn, so a plane ride arrives as a single observation
-- long after the previous one, and it is reading, not idleness.
--
-- This is BookOrbit's session-delta semantics reached from the other side. They
-- bracket a session on the client and post one `end - start` delta; that shape
-- was rejected for omnibus in #2139 because every reading surface would have to
-- learn to carry a percent first (the iOS reader posts a CFI and no percent at
-- all), and a session lost on a crashed tab takes its whole delta with it.
-- Deriving the same bracket from the position writes the clients already make
-- needs no client change and inherits the offline outboxes' durability.
--
-- Known residual, deliberate: a backtrack spanning a sitting boundary — go
-- back, put the book down, read forward tomorrow — still over-credits, because
-- a per-sitting clamp cannot net across sittings. Closing that needs signed
-- deltas or an explicit re-read boundary; see the discussion on #2394.

-- Renamed rather than added: it is the same slot, holding the same kind of
-- value, under one new rule — it no longer follows the reader backward mid
-- sitting. A second percent column would just be two answers to one question.
-- SQLite rewrites the column's CHECK constraint along with the rename.
ALTER TABLE reading_progress_marks RENAME COLUMN percent TO sitting_max_percent;

-- The sitting clock, deliberately *not* `updated_at`. Two differences, and both
-- matter: this one advances only on a real observation, where `updated_at`
-- carries `DEFAULT (strftime('%s','now'))` and is what `merge::transaction`'s
-- `dedupe_latest_wins` arbitrates on — so a merge or a maintenance write that
-- touched the row would silently end or extend a sitting if the two were one
-- column. And this one is clamped forward monotonically, so an observation that
-- arrives out of order (the off-request-path percent derivation landing late
-- with the position's older event time) cannot drag the boundary backward and
-- manufacture a gap.
--
-- Nullable, and deliberately left NULL on every existing row rather than
-- backfilled from `updated_at`. NULL reads as "no sitting in progress", which
-- re-baselines on the next observation — and that is what the existing rows
-- want, because each one holds a mark under the *old* last-position-seen
-- meaning. Seeding a clock from `updated_at` would let a recently-written one
-- carry that stale mark into a live sitting and charge the reader once more for
-- ground it had already counted, which is the bug this migration exists to end.
-- Nothing is lost by starting them cold: the first observation after the deploy
-- baselines, exactly as a book seen for the first time does.
ALTER TABLE reading_progress_marks ADD COLUMN sitting_observed_at INTEGER;
