//! Unit tests for the `taxonomy` resolve-or-insert helpers. The three helpers
//! are generated by the same `resolve_or_insert_simple!` macro, so we cover
//! all three contracts (insert, idempotency, case-insensitivity) on `series`
//! and spot-check the other two to catch a macro-expansion regression on
//! `publishers` (`name`) or `languages` (`code`).

use super::*;
use crate::pool::init_db;

#[tokio::test]
async fn resolve_or_insert_series_inserts_and_returns_id() {
    let pool = init_db("sqlite::memory:").await.unwrap();
    let mut tx = pool.begin().await.unwrap();
    let id = resolve_or_insert_series(&mut tx, "Science Fiction")
        .await
        .unwrap();
    assert!(id > 0, "expected a positive row id, got {id}");
    tx.commit().await.unwrap();

    let stored: String = sqlx::query_scalar("SELECT name FROM series WHERE id = ?")
        .bind(id)
        .fetch_one(&pool)
        .await
        .unwrap();
    assert_eq!(stored, "Science Fiction");
}

#[tokio::test]
async fn resolve_or_insert_series_is_idempotent_for_same_name() {
    let pool = init_db("sqlite::memory:").await.unwrap();
    let mut tx = pool.begin().await.unwrap();
    let id1 = resolve_or_insert_series(&mut tx, "Fantasy").await.unwrap();
    let id2 = resolve_or_insert_series(&mut tx, "Fantasy").await.unwrap();
    assert_eq!(id1, id2, "second insert must reuse the existing row id");
    tx.commit().await.unwrap();

    let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM series WHERE name = ?")
        .bind("Fantasy")
        .fetch_one(&pool)
        .await
        .unwrap();
    assert_eq!(count, 1, "expected exactly one series row, got {count}");
}

#[tokio::test]
async fn resolve_or_insert_series_collapses_case_variants_to_one_row() {
    // The `series.name` column is declared `COLLATE NOCASE` (see
    // migration 0002), so `INSERT OR IGNORE` treats case variants as
    // duplicates and the follow-up `SELECT … WHERE name = ?` resolves
    // back to the row stored under the first-seen case.
    let pool = init_db("sqlite::memory:").await.unwrap();
    let mut tx = pool.begin().await.unwrap();
    let id_mixed = resolve_or_insert_series(&mut tx, "Fantasy").await.unwrap();
    let id_lower = resolve_or_insert_series(&mut tx, "fantasy").await.unwrap();
    let id_upper = resolve_or_insert_series(&mut tx, "FANTASY").await.unwrap();
    assert_eq!(id_mixed, id_lower);
    assert_eq!(id_mixed, id_upper);
    tx.commit().await.unwrap();

    let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM series")
        .fetch_one(&pool)
        .await
        .unwrap();
    assert_eq!(count, 1, "case variants must not insert extra rows");

    // First-seen case is preserved — `INSERT OR IGNORE` is a no-op on the
    // case-different follow-ups, so the stored value is the original.
    let stored: String = sqlx::query_scalar("SELECT name FROM series WHERE id = ?")
        .bind(id_mixed)
        .fetch_one(&pool)
        .await
        .unwrap();
    assert_eq!(stored, "Fantasy");
}

#[tokio::test]
async fn resolve_or_insert_publisher_inserts_and_is_idempotent() {
    let pool = init_db("sqlite::memory:").await.unwrap();
    let mut tx = pool.begin().await.unwrap();
    let id1 = resolve_or_insert_publisher(&mut tx, "Penguin Random House")
        .await
        .unwrap();
    let id2 = resolve_or_insert_publisher(&mut tx, "Penguin Random House")
        .await
        .unwrap();
    assert!(id1 > 0);
    assert_eq!(id1, id2);
    tx.commit().await.unwrap();

    let stored: String = sqlx::query_scalar("SELECT name FROM publishers WHERE id = ?")
        .bind(id1)
        .fetch_one(&pool)
        .await
        .unwrap();
    assert_eq!(stored, "Penguin Random House");
}

#[tokio::test]
async fn resolve_or_insert_language_keys_off_the_code_column() {
    // `languages.code` is the keyed column (not `name`), so this test
    // also catches the macro accidentally targeting the wrong column.
    let pool = init_db("sqlite::memory:").await.unwrap();
    let mut tx = pool.begin().await.unwrap();
    let id_en = resolve_or_insert_language(&mut tx, "en").await.unwrap();
    let id_en_upper = resolve_or_insert_language(&mut tx, "EN").await.unwrap();
    let id_fr = resolve_or_insert_language(&mut tx, "fr").await.unwrap();
    assert!(id_en > 0);
    assert_eq!(id_en, id_en_upper, "code column is COLLATE NOCASE");
    assert_ne!(id_en, id_fr, "distinct codes must get distinct ids");
    tx.commit().await.unwrap();

    let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM languages")
        .fetch_one(&pool)
        .await
        .unwrap();
    assert_eq!(count, 2);
}
