version: "0.5"

processes:
  server:
    command: nix develop .#web --command dx serve --platform web --fullstack --port 3000 --package omnibus

  android:
    command: nix develop .#mobile --command dx serve --platform android --package omnibus-mobile
    disabled: true

  ios:
    command: nix develop .#mobile --command dx serve --platform ios --package omnibus-mobile
    disabled: true

  playwright:
    command: nix develop ../..#e2e --command npx playwright test --ui
    working_dir: ui_tests/playwright
    disabled: true
