#!/usr/bin/env bash
# Shared port-resolution helpers for the dev-server front doors.
#
# Sourced by scripts/dev-server-up.sh (daemonized, for agents) and
# scripts/dev-serve-fg.sh (foreground, for the `just serve` panes). Both
# answer the same question — which port does THIS worktree's server belong
# on — and a second copy of the walk would let the two front doors drift
# and hand one port to two worktrees.
#
# Callers must `cd` to the worktree root before sourcing; RUNTIME_DIR is
# relative so log paths stay short in messages.

# Workspace root for THIS run. Compared against the `repo_root` field
# /api/_health returns, so we can tell our own server apart from a sibling
# worktree's server bound to a port inside our window.
MY_REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

RUNTIME_DIR=".claude/runtime"

START_PORT="${PORT:-3000}"
# A 10-port window matches the per-worktree PORT stride flake.nix assigns,
# so the walk stays *inside* this worktree's window and can never wander
# into a sibling's range.
END_PORT=$((START_PORT + 9))

# Tighter timeouts than curl defaults so a misbehaving foreign process
# can't stall the probe sweep.
probe_health() {
    local port="$1"
    curl --silent --show-error --max-time 2 --connect-timeout 1 \
        "http://127.0.0.1:${port}/api/_health" 2>/dev/null || true
}

is_port_free() {
    local port="$1"
    # `lsof -iTCP -sTCP:LISTEN -P` exits non-zero when nothing's listening.
    ! lsof -iTCP:"$port" -sTCP:LISTEN -P >/dev/null 2>&1
}

is_omnibus_response() {
    # Matches the literal substring the /api/_health handler emits.
    echo "$1" | grep -q '"app"[[:space:]]*:[[:space:]]*"omnibus"'
}

# Pull the `repo_root` field from an /api/_health JSON body. Empty if the
# server is too old to expose it or the response is malformed.
extract_repo_root() {
    echo "$1" | sed -nE 's/.*"repo_root"[[:space:]]*:[[:space:]]*"([^"]*)".*/\1/p'
}

# Same as is_omnibus_response, but ALSO requires the server's reported
# `repo_root` to match MY_REPO_ROOT — i.e. "this is omnibus AND it's MY
# worktree's omnibus". Without this gate, two worktrees whose windows
# overlap would silently reuse each other's server.
is_my_omnibus_response() {
    is_omnibus_response "$1" || return 1
    local server_root
    server_root="$(extract_repo_root "$1")"
    [ -n "$server_root" ] && [ "$server_root" = "$MY_REPO_ROOT" ]
}

# Walk START_PORT..END_PORT and echo "<port>:<mode>", mode being `free` or
# `reuse`. Returns 1 when every candidate is held by a process we must not
# disturb.
#
# Pass --free-only to never return `reuse`: a foreground launcher is being
# asked to *run* a server, so adopting an already-running one is not an
# answer — it walks past its own server to the next free port instead.
choose_port() {
    local free_only=0
    [ "${1:-}" = "--free-only" ] && free_only=1

    local port
    for ((port = START_PORT; port <= END_PORT; port++)); do
        if is_port_free "$port"; then
            echo "$port:free"
            return 0
        fi
        local body server_root
        body="$(probe_health "$port")"
        if is_my_omnibus_response "$body"; then
            if [ "$free_only" -eq 1 ]; then
                echo "dev: port $port already serves this worktree; walking past it" >&2
                continue
            fi
            echo "$port:reuse"
            return 0
        fi
        if is_omnibus_response "$body"; then
            # Sibling worktree's omnibus server bound to this port. Don't
            # reuse it (different code, different DB) — walk to the next.
            server_root="$(extract_repo_root "$body")"
            echo "dev: port $port held by sibling worktree ${server_root:-<unknown>}, skipping" >&2
        fi
        # Port held by something that isn't omnibus, or by a sibling — skip.
    done
    return 1
}

# Publish the chosen port so Playwright, the ui-validate skill, and humans
# can pick it up with `source .claude/runtime/env.sh` instead of assuming
# 3000.
write_runtime_files() {
    local port="$1"
    mkdir -p "$RUNTIME_DIR"
    echo "$port" >"$RUNTIME_DIR/port"
    cat >"$RUNTIME_DIR/env.sh" <<EOF
# Generated by the omnibus dev-server launcher — source before running
# Playwright or driving the preview. Re-run dev-up/serve to refresh.
export OMNIBUS_PORT=$port
export PLAYWRIGHT_BASE_URL=http://127.0.0.1:$port
EOF
}
