#!/usr/bin/env bash
# Idempotent dev-server bring-up for Claude's ui-validate workflow and for
# anyone who wants a port-walking, "just give me a server" front door.
#
# What it does:
#   1. Probes 127.0.0.1:<port> starting at $PORT (default 3000), walking up
#      to PORT+20. Reuses an existing omnibus instance if /api/_health
#      identifies one; picks the first free port otherwise; exits 1 if every
#      candidate is held by a foreign process.
#   2. Verifies OMNIBUS_DEV_SEED_USER is set (otherwise the server boots
#      without a known admin login and `ui-validate` will fail at the
#      `/login` step). Tells the user to copy .env.example -> .env.
#   3. Starts `dx serve --platform web --fullstack --port <chosen> -p omnibus`
#      in the background. Output -> .claude/runtime/server.log, PID ->
#      .claude/runtime/server.pid. Polls /api/_health until 200 (90s cap).
#   4. Writes:
#        .claude/runtime/port      -> "<chosen>"
#        .claude/runtime/env.sh    -> exports OMNIBUS_PORT + PLAYWRIGHT_BASE_URL
#      So Claude and humans can `source .claude/runtime/env.sh` before
#      running `npx playwright test` or driving the preview.
#
# Re-running this script is safe — if /api/_health already says "omnibus"
# at the chosen port, we just reuse and re-emit the runtime files.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

RUNTIME_DIR=".claude/runtime"
mkdir -p "$RUNTIME_DIR"

START_PORT="${PORT:-3000}"
END_PORT=$((START_PORT + 20))

# Tighter timeouts than curl defaults so a misbehaving foreign process
# can't stall the probe sweep.
probe_health() {
    local port="$1"
    curl --silent --show-error --max-time 2 --connect-timeout 1 \
        "http://127.0.0.1:${port}/api/_health" 2>/dev/null || true
}

is_port_free() {
    local port="$1"
    # `lsof -iTCP -sTCP:LISTEN -P` exits non-zero when nothing's listening.
    ! lsof -iTCP:"$port" -sTCP:LISTEN -P >/dev/null 2>&1
}

is_omnibus_response() {
    # Matches the literal substring the /api/_health handler emits.
    echo "$1" | grep -q '"app"[[:space:]]*:[[:space:]]*"omnibus"'
}

choose_port() {
    local port
    for ((port = START_PORT; port <= END_PORT; port++)); do
        if is_port_free "$port"; then
            echo "$port:free"
            return 0
        fi
        local body
        body="$(probe_health "$port")"
        if is_omnibus_response "$body"; then
            echo "$port:reuse"
            return 0
        fi
        # Port is held by something that isn't omnibus — skip it.
    done
    return 1
}

write_runtime_files() {
    local port="$1"
    echo "$port" >"$RUNTIME_DIR/port"
    cat >"$RUNTIME_DIR/env.sh" <<EOF
# Generated by scripts/dev-server-up.sh — source before running Playwright
# or driving the preview. Re-run dev-up to refresh.
export OMNIBUS_PORT=$port
export PLAYWRIGHT_BASE_URL=http://127.0.0.1:$port
EOF
}

wait_for_health() {
    local port="$1"
    local deadline=$(($(date +%s) + 90))
    while [ "$(date +%s)" -lt "$deadline" ]; do
        local body
        body="$(probe_health "$port")"
        if is_omnibus_response "$body"; then
            echo "$body"
            return 0
        fi
        sleep 1
    done
    return 1
}

start_server() {
    local port="$1"

    # Without a seed user the freshly-booted server has no admin login and
    # the ui-validate skill can't proceed past /login. Fail fast with a
    # clear remediation rather than booting into an unusable state.
    if [ -z "${OMNIBUS_DEV_SEED_USER:-}" ]; then
        cat >&2 <<'EOF'
dev-up: OMNIBUS_DEV_SEED_USER is not set.
  -> copy .env.example to .env and re-enter `nix develop` (or `source .env`).
     The default value in .env.example is admin:omnibus-dev.
EOF
        exit 1
    fi

    # Export overrides for the child server. PORT and OMNIBUS_PUBLIC_ORIGIN
    # need to match the chosen port so origin_check accepts cookie POSTs
    # from the browser. OMNIBUS_DEV_SEED_USER is inherited from the dev
    # shell (.env via flake.nix shellHook).
    export PORT="$port"
    export OMNIBUS_PUBLIC_ORIGIN="http://localhost:$port"

    echo "dev-up: starting dx serve on port $port (log: $RUNTIME_DIR/server.log)" >&2
    # nohup detaches from this script's process group so `just dev-up` can
    # exit cleanly without taking the server with it. setsid would be
    # cleaner but isn't on macOS by default.
    nohup dx serve --platform web --fullstack --port "$port" --package omnibus \
        >"$RUNTIME_DIR/server.log" 2>&1 &
    local server_pid=$!
    echo "$server_pid" >"$RUNTIME_DIR/server.pid"

    if ! wait_for_health "$port" >/dev/null; then
        # Kill the orphan rather than leaving it bound to $port — a stale,
        # unhealthy process would block the next dev-up (or get "reused"
        # as if it were healthy if it manages to start serving later).
        if kill -0 "$server_pid" 2>/dev/null; then
            echo "dev-up: server did not become healthy within 90s; killing pid $server_pid" >&2
            kill "$server_pid" 2>/dev/null || true
            # Reap dx-wrap's grandchildren too (dx spawns the actual server
            # in a subprocess). pkill -P walks one level; that's enough
            # here because dx is the only child of $server_pid we care
            # about.
            pkill -P "$server_pid" 2>/dev/null || true
        fi
        rm -f "$RUNTIME_DIR/server.pid"
        echo "dev-up: tail the log for the underlying error:" >&2
        echo "  tail -n 50 $RUNTIME_DIR/server.log" >&2
        exit 1
    fi
}

main() {
    local choice port mode
    if ! choice="$(choose_port)"; then
        echo "dev-up: ports $START_PORT-$END_PORT are all held by non-omnibus processes." >&2
        echo "        Stop one of them or set PORT to a different starting point." >&2
        exit 1
    fi
    port="${choice%%:*}"
    mode="${choice##*:}"

    if [ "$mode" = "reuse" ]; then
        echo "dev-up: reusing existing omnibus server on port $port" >&2
    else
        start_server "$port"
    fi

    write_runtime_files "$port"

    local body build_id
    body="$(probe_health "$port")"
    build_id="$(echo "$body" | sed -nE 's/.*"build_id"[[:space:]]*:[[:space:]]*"([0-9]+)".*/\1/p')"

    echo "omnibus dev server ready at http://127.0.0.1:$port (build_id=$build_id); log in as ${OMNIBUS_DEV_SEED_USER:-<unset>}"
}

main "$@"
